name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: true
          cmake: true
          ninja: true
      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure

  sanitizers:
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined, thread]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
          ninja: true
      - run: >-
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_FLAGS=-fsanitize=${{ matrix.sanitizer }}
          -DCMAKE_EXE_LINKER_FLAGS=-fsanitize=${{ matrix.sanitizer }}
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure
